user_list:
    controller: WebSite\Controller\UserController:listUserAction
user_add:
    controller: WebSite\Controller\UserController:addUser
user_delete:
    controller: WebSite\Controller\UserController:deleteUser
user_log:
    controller: WebSite\Controller\UserController:logUser
user_show:
    controller: WebSite\Controller\UserController:showUserAction